/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    media: Media;
    auditLog: AuditLog;
    workflows: Workflow;
    'workflow-runs': WorkflowRun;
    users: User;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    auditLog: AuditLogSelect<false> | AuditLogSelect<true>;
    workflows: WorkflowsSelect<false> | WorkflowsSelect<true>;
    'workflow-runs': WorkflowRunsSelect<false> | WorkflowRunsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      'workflow-cron-executor': TaskWorkflowCronExecutor;
      'http-request-step': TaskHttpRequestStep;
      'create-document': TaskCreateDocument;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  content?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditLog".
 */
export interface AuditLog {
  id: string;
  post?: (string | null) | Post;
  user?: (string | null) | User;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Create and manage automated workflows.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflows".
 */
export interface Workflow {
  id: string;
  /**
   * Human-readable name for the workflow
   */
  name: string;
  /**
   * Optional description of what this workflow does
   */
  description?: string | null;
  triggers?:
    | {
        type?: ('collection-trigger' | 'webhook-trigger' | 'global-trigger' | 'cron-trigger') | null;
        parameters?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * Collection that triggers the workflow
         */
        __builtin_collectionSlug?: ('posts' | 'media') | null;
        /**
         * Collection operation that triggers the workflow
         */
        __builtin_operation?: ('create' | 'delete' | 'read' | 'update') | null;
        /**
         * URL path for the webhook (e.g., "my-webhook"). Full URL will be /api/workflows-webhook/my-webhook
         */
        __builtin_webhookPath?: string | null;
        /**
         * Global that triggers the workflow
         */
        __builtin_global?: string | null;
        /**
         * Global operation that triggers the workflow
         */
        __builtin_globalOperation?: 'update' | null;
        /**
         * Cron expression for scheduled execution (e.g., "0 0 * * *" for daily at midnight)
         */
        __builtin_cronExpression?: string | null;
        /**
         * Timezone for cron execution (e.g., "America/New_York", "Europe/London"). Defaults to UTC.
         */
        __builtin_timezone?: string | null;
        /**
         * JSONPath expression that must evaluate to true for this trigger to execute the workflow (e.g., "$.trigger.doc.status == 'published'")
         */
        condition?: string | null;
        id?: string | null;
      }[]
    | null;
  steps?:
    | {
        step?: ('http-request-step' | 'create-document') | null;
        name?: string | null;
        /**
         * The URL to make the HTTP request to
         */
        url?: string | null;
        /**
         * HTTP method to use
         */
        method?: ('GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH') | null;
        /**
         * HTTP headers as JSON object (e.g., {"Content-Type": "application/json"})
         */
        headers?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * Request body data. Use JSONPath to reference values (e.g., {"postId": "$.trigger.doc.id", "title": "$.trigger.doc.title"})
         */
        body?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * Request timeout in milliseconds (default: 30000)
         */
        timeout?: number | null;
        authentication?: {
          /**
           * Authentication method
           */
          type?: ('none' | 'bearer' | 'basic' | 'apikey') | null;
          /**
           * Bearer token value
           */
          token?: string | null;
          /**
           * Basic auth username
           */
          username?: string | null;
          /**
           * Basic auth password
           */
          password?: string | null;
          /**
           * API key header name (e.g., "X-API-Key")
           */
          headerName?: string | null;
          /**
           * API key value
           */
          headerValue?: string | null;
        };
        /**
         * Number of retry attempts on failure (max: 5)
         */
        retries?: number | null;
        /**
         * Delay between retries in milliseconds
         */
        retryDelay?: number | null;
        /**
         * The collection slug to create a document in
         */
        collectionSlug?: string | null;
        /**
         * The document data to create. Use JSONPath to reference trigger data (e.g., {"title": "$.trigger.doc.title", "author": "$.trigger.doc.author"})
         */
        data?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * Create as draft (if collection has drafts enabled)
         */
        draft?: boolean | null;
        /**
         * Locale for the document (if localization is enabled)
         */
        locale?: string | null;
        /**
         * Step names that must complete before this step can run
         */
        dependencies?: string[] | null;
        /**
         * JSONPath expression that must evaluate to true for this step to execute (e.g., "$.trigger.doc.status == 'published'")
         */
        condition?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-runs".
 */
export interface WorkflowRun {
  id: string;
  /**
   * Reference to the workflow that was executed
   */
  workflow: string | Workflow;
  /**
   * Version of the workflow that was executed
   */
  workflowVersion: number;
  /**
   * Current execution status
   */
  status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';
  /**
   * When execution began
   */
  startedAt: string;
  /**
   * When execution finished
   */
  completedAt?: string | null;
  /**
   * Total execution time in milliseconds
   */
  duration?: number | null;
  context?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Input data provided when the workflow was triggered
   */
  inputs:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Final output data from completed steps
   */
  outputs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * User, system, or trigger type that initiated execution
   */
  triggeredBy: string;
  /**
   * Array of step execution results
   */
  steps:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Error message if workflow execution failed
   */
  error?: string | null;
  /**
   * Detailed execution logs
   */
  logs:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'workflow-cron-executor' | 'http-request-step' | 'create-document';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'workflow-cron-executor' | 'http-request-step' | 'create-document') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'auditLog';
        value: string | AuditLog;
      } | null)
    | ({
        relationTo: 'workflows';
        value: string | Workflow;
      } | null)
    | ({
        relationTo: 'workflow-runs';
        value: string | WorkflowRun;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: string | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditLog_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  post?: T;
  user?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflows_select".
 */
export interface WorkflowsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  triggers?:
    | T
    | {
        type?: T;
        parameters?: T;
        __builtin_collectionSlug?: T;
        __builtin_operation?: T;
        __builtin_webhookPath?: T;
        __builtin_global?: T;
        __builtin_globalOperation?: T;
        __builtin_cronExpression?: T;
        __builtin_timezone?: T;
        condition?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        step?: T;
        name?: T;
        url?: T;
        method?: T;
        headers?: T;
        body?: T;
        timeout?: T;
        authentication?:
          | T
          | {
              type?: T;
              token?: T;
              username?: T;
              password?: T;
              headerName?: T;
              headerValue?: T;
            };
        retries?: T;
        retryDelay?: T;
        collectionSlug?: T;
        data?: T;
        draft?: T;
        locale?: T;
        dependencies?: T;
        condition?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-runs_select".
 */
export interface WorkflowRunsSelect<T extends boolean = true> {
  workflow?: T;
  workflowVersion?: T;
  status?: T;
  startedAt?: T;
  completedAt?: T;
  duration?: T;
  context?: T;
  inputs?: T;
  outputs?: T;
  triggeredBy?: T;
  steps?: T;
  error?: T;
  logs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskWorkflow-cron-executor".
 */
export interface TaskWorkflowCronExecutor {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskHttp-request-step".
 */
export interface TaskHttpRequestStep {
  input: {
    /**
     * The URL to make the HTTP request to
     */
    url: string;
    /**
     * HTTP method to use
     */
    method?: ('GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH') | null;
    /**
     * HTTP headers as JSON object (e.g., {"Content-Type": "application/json"})
     */
    headers?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Request body data. Use JSONPath to reference values (e.g., {"postId": "$.trigger.doc.id", "title": "$.trigger.doc.title"})
     */
    body?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Request timeout in milliseconds (default: 30000)
     */
    timeout?: number | null;
    authentication?: {
      /**
       * Authentication method
       */
      type?: ('none' | 'bearer' | 'basic' | 'apikey') | null;
      /**
       * Bearer token value
       */
      token?: string | null;
      /**
       * Basic auth username
       */
      username?: string | null;
      /**
       * Basic auth password
       */
      password?: string | null;
      /**
       * API key header name (e.g., "X-API-Key")
       */
      headerName?: string | null;
      /**
       * API key value
       */
      headerValue?: string | null;
    };
    /**
     * Number of retry attempts on failure (max: 5)
     */
    retries?: number | null;
    /**
     * Delay between retries in milliseconds
     */
    retryDelay?: number | null;
  };
  output: {
    /**
     * HTTP status code
     */
    status?: number | null;
    /**
     * HTTP status text
     */
    statusText?: string | null;
    /**
     * Response headers
     */
    headers?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Response body
     */
    body?: string | null;
    /**
     * Parsed response data (if JSON)
     */
    data?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Request duration in milliseconds
     */
    duration?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreate-document".
 */
export interface TaskCreateDocument {
  input: {
    /**
     * The collection slug to create a document in
     */
    collectionSlug: string;
    /**
     * The document data to create. Use JSONPath to reference trigger data (e.g., {"title": "$.trigger.doc.title", "author": "$.trigger.doc.author"})
     */
    data:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Create as draft (if collection has drafts enabled)
     */
    draft?: boolean | null;
    /**
     * Locale for the document (if localization is enabled)
     */
    locale?: string | null;
  };
  output: {
    /**
     * The created document
     */
    doc?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * The ID of the created document
     */
    id?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}